release: ./mvnw flyway:migrate -Dflyway.configFiles=myFlywayConfig.properties
web: java -jar -Dserver.port=$PORT -Dspring.profiles.active=prod $JAVA_OPTS target/backend-0.0.1-SNAPSHOT.jar
worker: python3 nlp/src/new/extractor.py